reenable ansible check

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -303,17 +303,17 @@ jobs:
       - run:
           # prettier-ignore
           name: Trigger Ansible Tower Deployment
-          command: "curl -s -o response.json -X POST \"https://ansible-tower.princeton.edu/api/v2/job_templates/89/launch/\" --header \"Content-Type: application/json\" --header \"Authorization: Bearer $TOWER_TOKEN\" -d '{\"credential_passwords\":{},\"extra_vars\":{\"repo_name\":\"tigerdata-app\", \"runtime_env\":\"ci\"}}'"
-      # - run:
-      #     name: Check Ansible Tower Response
-      #     command: |
-      #       if grep -q '"status": "successful"' response.json; then
-      #         echo "Deployment successful"
-      #       else
-      #         echo "Deployment failed"
-      #         cat response.json
-      #         exit 1
-      #       fi
+          command: "curl -v -s -o response.json -X POST \"https://ansible-tower.princeton.edu/api/v2/job_templates/89/launch/\" --header \"Content-Type: application/json\" --header \"Authorization: Bearer $TOWER_TOKEN\" -d '{\"credential_passwords\":{},\"extra_vars\":{\"repo_name\":\"tigerdata-app\", \"runtime_env\":\"ci\"}}'"
+      - run:
+          name: Check Ansible Tower Response
+          command: |
+            if grep -q '"status": "successful"' response.json; then
+              echo "Deployment successful"
+            else
+              echo "Deployment failed"
+              cat response.json
+              exit 1
+            fi
 
   done:
     docker:
